/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cenxui' at '11/16/16 10:40 AM' with Gradle 2.14.1
 *
 * @author cenxui, @date 11/16/16 10:40 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
